
name: mysql

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - local_network

networks:
  local_network:
    name: local_network

volumes:
  data:

