
name: keycloak

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    depends_on: 
      - postgres
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=pass
    ports:
      - 8080:8080
    networks:
      - ecommerce_network

  postgres:
    image: postgres
    container_name: keycloak_postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

networks:
  ecommerce_network:
    external: true

volumes:
  data:

