version: '3'

volumes:
  mysql_data:
  keycloak_data:

networks:
  mysql_network:

services:
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - mysql_network

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=keycloak
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
