
name: basic_layered_net_api

services:
  basic_layered_net_api:
    image: alperyesilyurt/basic_layeredapi:latest
    container_name: basic_layered_net_api
    ports:
      - 7207:443
      - 5207:80
    environment:
      DB_CON_STR: server=mysql;port=3306;database=BasicLayeredService;user=root;password=pass;
      OIDC_AUTHORITY: http://keycloak:8080/realms/local_realm
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ELK_URL: http://elasticsearch:9200/
      ELK_PASS: alper
      ELK_USER: alper
      LOG_LEVEL: info
    networks:
      - local_network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

networks:
  local_network:
    name: local_network