
name: mysql

volumes:
  data:

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - network1

networks:
  network1:
    name: local_network

