
name: elk

volumes:
  data:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=alper
      - ELASTIC_PASSWORD=alper
      - xpack.security.enabled=false 
      - xpack.security.enrollment.enabled=false
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - network1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=alper
      - ELASTICSEARCH_PASSWORD=alper
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - network1

networks:
  network1:
    name: local_network
    external: true