
name: ecommerce_all

services:
  itemapi:
    image: alperyesilyurt/ecommerce_itemapi:latest
    container_name: ecommerce_all_itemapi
    depends_on:
      - itemapi_mysql
    ports:
      - 7207:443
      - 5207:80
    environment:
      DB_CON_STR: server=ecommerce_all_itemapi_mysql;port=3306;database=ECommerceItemService;user=root;password=pass;
      OIDC_AUTHORITY: http://ecommerce_all_keycloak:8080/auth/realms/local_realm
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ELK_URL: http://elasticsearch:9200/
      ELK_PASS: alper
      ELK_USER: alper
      LOG_LEVEL: info
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  itemapi_mysql:
    image: mysql
    container_name: ecommerce_all_itemapi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - itemapi_data:/var/lib/mysql

  keycloak:
    image: keycloak/keycloak
    container_name: ecommerce_all_keycloak
    command: ["start-dev"]
    depends_on: 
      - keycloak_postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=ecommerce_all_keycloak_postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=pass
    ports:
      - 8080:8080

  keycloak_postgres:
    image: postgres
    container_name: ecommerce_all_keycloak_postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: ecommerce_all_elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=alper
      - ELASTIC_PASSWORD=alper
      - xpack.security.enabled=false 
      - xpack.security.enrollment.enabled=false
    volumes:
      - elk_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: ecommerce_all_kibana
    environment:
      - ELASTICSEARCH_USERNAME=alper
      - ELASTICSEARCH_PASSWORD=alper
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  itemapi_data:
  keycloak_data:
  elk_data: