
name: postgres

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    networks:
      - local_network

networks:
  local_network:
    external: true

volumes:
  postgres_data:


