
name: keycloak

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    depends_on: 
      - keycloak_postgres
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=pass
    ports:
      - 8080:8080
    networks:
      - ecommerce_network
      - keycloak_network

  keycloak_postgres:
    image: postgres
    container_name: keycloak_postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: keycloak
    networks:
      - keycloak_network

networks:
  ecommerce_network:
    name: ecommerce_network
  keycloak_network:
    name: keycloak_network

volumes:
  keycloak_data:
    name: keycloak_data

