version: '3'
name: mysql

volumes:
  data:

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
