
name: postgres

volumes:
  data:

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    networks:
      - network1

networks:
  network1:
    name: local_network
    external: true


