version: '3.8'
name: pgre

volumes:
  data:

services:
  pgre:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: root_db

