version: '3'

volumes:
  keycloak_data:

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data


