
name: mysql

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    name: ecommerce_network

volumes:
  mysql_data:
    name: mysql_data

