version: '3'
name: keycloak

volumes:
  data:

services:
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8081:8080
    volumes:
      - data:/opt/jboss/keycloak/standalone/data


