
name: keycloak

services:
  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    command: ["start-dev"]
    depends_on: 
      - postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=pass
    ports:
      - 8080:8080
    networks:
      - local_network

  postgres:
    image: postgres
    container_name: keycloak_postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: keycloak

networks:
  local_network:
    name: local_network
    
volumes:
  data:

