version: '3'

volumes:
  mysql_data:

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
