version: "3.4"

name: ecommerce_itemapi

services:
  ecommerce_itemapi:
    image: alperyesilyurt/ecommerce_itemapi:latest
    container_name: ecommerce_itemapi
    depends_on:
      - mysql
    ports:
      - 7207:443
      - 5207:80
    environment:
      DB_CON_STR: server=ecommerce_itemapi_mysql;port=3306;database=ECommerceItemService;user=root;password=pass;
      OIDC_AUTHORITY: http://keycloak:8080/auth/realms/local_realm
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ELK_URL: http://elasticsearch:9200/
      ELK_PASS: alper
      ELK_USER: alper
      LOG_LEVEL: info
    networks:
      - ecommerce_network
      - ecommerce_itemapi_network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mysql:
    image: mysql
    container_name: ecommerce_itemapi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    networks:
      - ecommerce_itemapi_network
    volumes:
      - ecommerce_itemapi_data:/var/lib/mysql

networks:
  ecommerce_network:
    external: true
  ecommerce_itemapi_network:
    name: ecommerce_itemapi_network

volumes:
  ecommerce_itemapi_data:
    name: ecommerce_itemapi_data