
name: ecommerce

services:
  ecommerce_itemapi:
    image: alperyesilyurt/ecommerce_itemapi:latest
    container_name: ecommerce_itemapi
    depends_on:
      - ecommerce_itemapi_mysql
    ports:
      - 7207:443
      - 5207:80
    environment:
      DB_CON_STR: server=ecommerce_itemapi_mysql;port=3306;database=ECommerceItemService;user=root;password=pass;
      OIDC_AUTHORITY: http://keycloak:8080/auth/realms/local_realm
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ELK_URL: http://elasticsearch:9200/
      ELK_PASS: alper
      ELK_USER: alper
      LOG_LEVEL: info
    networks:
      - ecommerce_network
      - ecommerce_itemapi_network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ecommerce_itemapi_mysql:
    image: mysql
    container_name: ecommerce_itemapi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    networks:
      - ecommerce_itemapi_network
    volumes:
      - ecommerce_itemapi_data:/var/lib/mysql

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    depends_on: 
      - keycloak_postgres
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=pass
    ports:
      - 8080:8080
    networks:
      - ecommerce_network
      - keycloak_network

  keycloak_postgres:
    image: postgres
    container_name: keycloak_postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    networks:
      - keycloak_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=alper
      - ELASTIC_PASSWORD=alper
      - xpack.security.enabled=false 
      - xpack.security.enrollment.enabled=false
    volumes:
      - elk_data:/usr/share/elasticsearch/data
    networks:
      - ecommerce_network
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=alper
      - ELASTICSEARCH_PASSWORD=alper
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk_network

networks:
  ecommerce_network:
    name: ecommerce_network
  ecommerce_itemapi_network:
    name: ecommerce_itemapi_network
  keycloak_network:
    name: keycloak_network
  elk_network:
    name: elk_network

volumes:
  ecommerce_itemapi_data:
    name: ecommerce_itemapi_data
  keycloak_data:
    name: keycloak_data
  elk_data:
    name: elk_data